### ISSUE TITLE
libsl_zed.so error on TX1 and OpenCV 3.1

### ISSUE THREAD

**Issue by ankitdhall** [stereolabs/zed-opencv#12]
Hello,

I'm trying to build the opencv example on a JETSON TX1, running R24 (release), REVISION: 1.0, GCID: 7164062, BOARD: t210ref, EABI: aarch64, DATE: Tue May 17 23:37:30 UTC 2016. The board has the GNU 4.8.4 compiler, CUDA 7.0 and is running OpenCV 3.1.

Is the  ZED_SDK_Linux_JTX1_v1.0.0b compatible with the above configurations? 

When I try to build the code I get the following error:
`/usr/local/zed/lib/libsl_zed.so: error adding symbols: File in wrong format`

I also get the following warnings
`Scanning dependencies of target ZED_with_OpenCV
[100%] Building CXX object CMakeFiles/ZED_with_OpenCV.dir/src/main.o
/media/ubuntu/f79d711d-0cef-4d5b-ac43-e01e1684fa56/code/zed-opencv/src/main.cpp: In function ‘void onMouseCallback(int32_t, int32_t, int32_t, int32_t, void*)’:
/media/ubuntu/f79d711d-0cef-4d5b-ac43-e01e1684fa56/code/zed-opencv/src/main.cpp:70:90: warning: too many arguments for format [-Wformat-extra-args]
                 printf("\n%s is too far.\n", data->name.c_str(), dist, data->unit.c_str());
                                                                                          ^
/media/ubuntu/f79d711d-0cef-4d5b-ac43-e01e1684fa56/code/zed-opencv/src/main.cpp:72:92: warning: too many arguments for format [-Wformat-extra-args]
                 printf("\n%s is too close.\n", data->name.c_str(), dist, data->unit.c_str());
                                                                                            ^
/media/ubuntu/f79d711d-0cef-4d5b-ac43-e01e1684fa56/code/zed-opencv/src/main.cpp:74:92: warning: too many arguments for format [-Wformat-extra-args]
                 printf("\n%s not avaliable\n", data->name.c_str(), dist, data->unit.c_str());
                                                                                            ^
Linking CXX executable "ZED with OpenCV"
/usr/local/zed/lib/libsl_zed.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [ZED with OpenCV] Error 1
make[1]: *** [CMakeFiles/ZED_with_OpenCV.dir/all] Error 2
make: *** [all] Error 2`

Thanks in advance.

**Comment by adujardin** [comment]
Hi,

The new release of the Jetson driver package (R24) introduced 64 bits support, however, we currently only support the 32 bits version on the TX1 (the only one provided before).

For the next release, we will probably provide the 2 versions. 
Sorry about that, for now, please use the 32 bits version.
