### ISSUE TITLE
How to read svo files without CUDA?

### ISSUE THREAD

**Issue by chuong** [stereolabs/zed-opencv#13]
Since ZED SDK depends on CUDA, it is difficult to process *.svo files on PC without an Nvidia GPU, even just to read images. Is there any example code to do this? What is the format of *.svo files?

**Comment by adujardin** [comment]
Hi,

The only way to read an SVO file without CUDA is to open it with ZED Explorer. You can't open a .svo file from the code without the ZED SDK.

If you want to record images and process it without the ZED SDK, you should record a video file (AVI or something similar).

**Comment by chuong** [comment]
Thanks @adujardin for the suggestion. I can now access the camera as a normal webcam with OpenCV and save images in any format.
