### ISSUE TITLE
Are the images undistorted and sznchronized?

### ISSUE THREAD

**Issue by M1234Thomas** [stereolabs/zed-opencv#20]
Hello,
It is clear from the API documentation that the function zed->retrieveImage() returns the rectified images.
Are these synchronized and un-distorted as well? 
I need to use synchronized, rectified un-distorted images for my work.

**Comment by sl-braun** [comment]
Hi,

Rectified images means that they are undistorted as well. 
Regarding the synchronisation, the ZED streams side by side (Left + Right) image which are perfectly synchronized (through hardware clock) which means that any retrieve*() function will be synchronized after a grab call.

example : 

```
if (zed->grab()==0)
{
   zed->retrieveImage(LEFT);
   zed->retrieveImage(RIGHT);  // --> (requires a copy) : synchronized to Left image
   zed->retrieveMeasure(DISPARITY/DEPTH/CONFIDENCE...);  // --> (requires a copy) : synchronized and mapped to Left image
  
}
```

Best,
/*OB*/
