### ISSUE TITLE
opencv error:no opengl suport

### ISSUE THREAD

**Issue by DamonMIN** [stereolabs/zed-opencv#21]
![problem](https://cloud.githubusercontent.com/assets/14936902/20511728/8f54e8f8-b0b5-11e6-9473-99856ea4110a.png)
when I run the zed-opencv code as what instruction said, there was an error. Then, I configurated opengl on my windows, it still existed. @adujardin

**Comment by adujardin** [comment]
Hi,

You can solve this issue by removing OpenGL support in the display. It is not essential and only provides a minor performance boost for `imshow`.

To remove it simply remove the flag `cv::WINDOW_OPENGL` [here](https://github.com/stereolabs/zed-opencv/blob/master/src/main.cpp#L174) and [here](https://github.com/stereolabs/zed-opencv/blob/master/src/main.cpp#L176) (that gives you for example : `cv::namedWindow(mouseStruct.name, cv::WINDOW_AUTOSIZE);`)
