### ISSUE TITLE
getSDKVersion() crash

### ISSUE THREAD

**Issue by bnascimento** [stereolabs/zed-opencv#24]
Hello guys, under windows x64 right now, using sdk version 1.1.1
the following throws a crash inside sdk lib:

_std::string sdkVersion = zed->getSDKVersion();_

Any hints?

Cheers,
Bruno

**Comment by sl-braun** [comment]
Similar to #22 : Did you build in Debug or Release?

**Comment by pavloblindnology** [comment]
Hello,
I'm using SDK 2.1, windows 10 x64.
The following throws a crash in Debug while automatically cleaning the sl::String on exiting the scope.
Note, there are no std:string nor "const char *" used.
> sl::String sdkVersion = sl::Camera::getSDKVersion();
