### ISSUE TITLE
Can it support opencv 3.2?

### ISSUE THREAD

**Issue by yxftju** [stereolabs/zed-opencv#29]
Recently I try ros with opencv 3.2 ,but it seems that it only can use with 3.1 . Can the SDK support with 3.2 since there are not many difference between 3.1 and 3.2?

**Comment by mtee** [comment]
Well, you can try to create copies of opencv libraries in /usr/local/lib and rename them from libopencv_*.so.3.2 to libopencv_*.so.3.1. I got ZED Explorer working this way, never tried it with ROS though.

**Comment by yxftju** [comment]
I did this operation two, but I found that some of zed examples still didn't work
