### ISSUE TITLE
ZED SDK compatible with Opencv 3.0?

### ISSUE THREAD

**Issue by won13y** [stereolabs/zed-opencv#3]
I am using ZED stereo camera with NVIDIA TK1 using openCV 2.4.9

I was wondering whether ZED can be used along with openCV >3.0?

**Comment by adujardin** [comment]
Hi,
Unfortunately, no, the ZED SDK is not compatible with OpenCV 3 yet. Especially for the Jetson K1/X1, we support the optimized version provided by NVIDIA (OpenCV 2.4).

However if you can't use 2.4 and you need OpenCV 3 for your application, it should be possible to link your program with both OpenCV 2.4 and OpenCV 3 at the same time.
