### ISSUE TITLE
Reading .svo files in ''zed-opencv'' main.cpp

### ISSUE THREAD

**Issue by abhishekravia** [stereolabs/zed-opencv#44]
I would like to read a pre-recorded .svo file in my code developed based on zed-opencv example.
Is there any sample code snippet available for the same?
Thanks.

**Comment by WASCHMASCHINE** [comment]
If you specify the file path of the SVO in the sl::InitParameters (svo_input_filename) it will work. One code line change. You should have checked the other samples.

**Comment by abhishekravia** [comment]
@WASCHMASCHINE Thanks for the solution.
