### ISSUE TITLE
How to get the GpuMat of depth image?

### ISSUE THREAD

**Issue by DreamsZM** [stereolabs/zed-opencv#47]
I wish to get the GpuMat of depth image,what should I do?

**Comment by WASCHMASCHINE** [comment]
Look at the sample code: https://github.com/stereolabs/zed-examples

**Comment by DreamsZM** [comment]
@WASCHMASCHINE after get zed.retrieveMeasure(gpu_depth, sl::MEASURE_DEPTH, sl::MEM_GPU),how to transform the cv::gpu::GpuMat?

**Comment by sl-braun** [comment]
Use cudaMemcpy to copy the GPU data of sl::Mat (using getPtr<sl::float1>(MEM_GPU)) to the gpu data of the gpuMat (.data)

**Comment by DreamsZM** [comment]
`sl::Mat inputDepthMat;
zed.retrieveImage(inputDepthMat, sl::VIEW_DEPTH, sl::MEM_GPU);
......
cv::gpu::GpuMat inputDepthMat_GPU;
cudaMemcpy2D(inputDepthMat_GPU.data, sizeof(float), inputDepthMat.getPtr<sl::uchar1>(sl::MEM_GPU), sizeof(float), 
		         inputDepthMat.getWidth(), inputDepthMat.getHeight(), cudaMemcpyDeviceToDevice);`

@sl-braun @WASCHMASCHINE

**Comment by liprin1129** [comment]
I did like this below, but not working...
`		cudaMemcpy2D(
				this->_gpuMat.data,
				this->_gpuMat.step * sizeof(float3),
				this->_zedMat.getPtr<sl::uchar1>(sl::MEM_GPU),
				this->_zedMat.getStepBytes(sl::MEM_GPU),
				this->_zedMat.getWidth() * sizeof(sl::uchar4),
				this->_zedMat.getHeight(),
				cudaMemcpyDeviceToDevice
				);`
