### ISSUE TITLE
downloading ZED SDK and viewing Depth map 

### ISSUE THREAD

**Issue by HamdaAlahmed** [stereolabs/zed-opencv#5]
Hi, 

I and facing a problem while downloading the ZED SDK, it says that the ZED is not connected to an internet. I can view the ZED explorer but the depth viewer is not appearing. 
I need to view the Depth map but I am lost, how I will be able to do that? 

thanks

**Comment by adujardin** [comment]
Hi, 

The ZED SDK needs the calibration file for the camera.
The problem can appear when there is no internet connection during the ZED SDK installation or if you're behind a proxy. 
In that case, could you tell me your serial number? You can find it using the ZED Explorer or on the cable.
