### ISSUE TITLE
Zed focal

### ISSUE THREAD

**Issue by LaiAmy** [stereolabs/zed-opencv#51]
Hi
How can I get zed camera's focal in pixels ?
What is the focal value in HD720 (1280x720) ?
Thank you .

**Comment by adujardin** [comment]
Hi,
You can find the calibration information with ZED Explorer (`Settings -> Calibration`) or directly in the calibration file (LEFT_CAM_HD for HD720) : 
- on Linux `/usr/local/zed/settings/SNXXXX.conf` 
- on Windows `C:\Users\YOUR_USER_NAME\AppData\Roaming\Stereolabs\settings\SNXXXX.conf`.

**Comment by LaiAmy** [comment]
Hi~
Ok , I find it . 
Thank you so much.
