### ISSUE TITLE
Are the ZED images from the ZED SDK rectified?

### ISSUE THREAD

**Issue by LUCASLLA** [stereolabs/zed-opencv#54]
Hi, I'm starting my studies in computer vision, and I'm working with a ZED camera. I successfully installed the last version of the ZED SDK (v.2.3.3 with CUDA 9.1 on Ubuntu 16) and everything seems to work fine.

I'm now trying to take pictures from the ZED camera using the SDK (left and right pictures), and trying to reconstruct the point cloud scene from the pictures not using the point cloud I can generate on the ZED Depth Viewer tool from the SDK. 

I already started with some problem, that the Zed Depth Viewer doesnt save the left and right pictures individually, they are saved into a single image side-by-side and I have to cut the image into two, but ok, this is a small inconvenience.

But now, I would like to know some things that are now clear to me yet.

To build the point cloud, I need to know if the images from the ZED Camera that I take on the Zed Depth Viewer (or Zed Explorer) are rectified, cause I'm using another algorithm to build the Disparity map from the images from the Zed SDK and the disparity map is totally broken, what indicates to me that the images are not really rectified, but I'm not sure yet. The algorithm I'm using can create the disparity map of some other pair of stereo images with success, but my images from the ZED camera are always having some broken disparity map.

On the same screen from the ZED Depth Viewer, I can see the depth map (in real time), and it looks ok, not bad as the disparity map I'm generating from the pictures that I save from the SDK and try to generate with the other algorithm.

How can I get sure if the ZED Depth Viewer images that I took are really rectified?

**Comment by P-yver** [comment]
Hi,
The SDK provides rectified images, unless you specify it, e.g.  _VIEW_LEFT_UNRECTIFIED_.
So the Depth Viewer gives you rectified images that can be saved side by side or seperated whereas the Explorer does not use de the SDK so it can only save UNrectified images.
