### ISSUE TITLE
Zed  focal (fz)

### ISSUE THREAD

**Issue by GITSHOHOKU** [stereolabs/zed-opencv#59]
I can get fx and fy in calibration data. I use the rectify image which has same fx and fy.To calculate the depth how can I know the focal(fz) of zed with resolution equals 1280x720
Thanks a lot

**Comment by WASCHMASCHINE** [comment]
Check this out:

https://github.com/stereolabs/zed-opencv/issues/39

**Comment by GITSHOHOKU** [comment]
@WASCHMASCHINE 
  My bad  I should search it before I asked  thanks !
