### ISSUE TITLE
NO GPU DECTECTED

### ISSUE THREAD

**Issue by AdamPengG** [stereolabs/zed-opencv#67]
I have installed cuda 10.But when I run the program the terminal shows NO GPU DECTECTED.

![cuda 10](https://user-images.githubusercontent.com/45864105/50394834-2d216780-079b-11e9-990f-51168e77d076.png)

![no_gpu](https://user-images.githubusercontent.com/45864105/50394748-6efdde00-079a-11e9-82f3-e1bfb639892a.png)
![gpu](https://user-images.githubusercontent.com/45864105/50394747-6e654780-079a-11e9-8bf3-bb07547dfe0e.png)

**Comment by AdamPengG** [comment]
HI!

**Comment by lyshuga** [comment]
Solved by plugging the camera into another port. In my case, I have changed from a USB 2.0 port to USB 3.0 one
