### ISSUE TITLE
Problem only in Desktop folder(ZED SDK >> Resolution not yet available)

### ISSUE THREAD

**Issue by wkyoun** [stereolabs/zed-opencv#7]
I have successfully run zed-opencv example in /usr/local/zed/sample/Y/cpu folder

but when I copy the same folder(zed-opencv) in Desktop folder,

it always results in following error:

ZED SDK >> Resolution not yet available

, which means that ZED is not available.

But, zed-opencv example in /usr/local/zed/sample/Y/cpu folder always work correctly.

I don't know why.

It seems to me that this problem might be related to authority problem?

**Comment by adujardin** [comment]
Hi, 

Normally, this error appears on the Jetson when the resolution is set higher than 720p (excluded). Could you check the resolution in the main file?

**Comment by won13y** [comment]
It is the same source file that work correctly in  /usr/local/zed/sample/Y/cpu folder, 

but the very same source file copied in Desktop folder produces the following errors:

ZED SDK >> Resolution not yet available

In the main file,

the resolution is set to be VGA.
