### ISSUE TITLE
运行zed-opencv.py时显示No module named 'pyzed.sl'错误

### ISSUE THREAD

**Issue by zhengjian0224** [stereolabs/zed-opencv#70]
在按照Readme.txt配置好环境后运行zed-opencv.py时总是显示No module named 'pyzed.sl'错误，请问该怎么修改？

**Comment by zhengjian0224** [comment]
已解决，谢谢

**Comment by FrankP89** [comment]
How did you fix it?

**Comment by ccsmm78** [comment]
Do not install pyzed using "pip install pyzed"

Instead of pip, run following to install it
# In your virtualenv,
$ pip uninstall pyzed  # (optional)
$ cd /usr/local/zed/​  # You need to install zed SDK in advance to reach here.
$ python get_python_api.py​
