### ISSUE TITLE
Reprojection from pixel coordinates to 3D world coordinates

### ISSUE THREAD

**Issue by AmerSam265** [stereolabs/zed-opencv#86]
Hello,
I am wondering how can I get the 3D world coordinates from pixel coordinates and ZED camera parameters, I know that we can get them directly using sl.MEASURE.XYZRGBA but I want to know how it is done mathematicaly ?
Thank you in advance!

**Comment by P-yver** [comment]
Hi,
the forumal, for a `sl::CalibrationParameters::calibration_parameters` cam  (not `sl::CalibrationParameters::calibration_parameters_raw`) for a pixel p is and :
depth = cam.fx * cam.baseline / disparity;
X = (p.x - cam.cx) *  depth / cam.fx
Y = (p.y - cam.cy) *  depth / cam.fy
Z = depth
