### ISSUE TITLE
retrieve_measure arguments switched?

### ISSUE THREAD

**Issue by bastidererste** [stereolabs/zed-opencv#88]
I think the retreieve_measure arguments are switched in these two functions: 

https://github.com/stereolabs/zed-opencv/blob/d8ffafc5b8fbabf8504102bdfb22caad073f04f2/python/zed-opencv.py#L40-L43

https://github.com/stereolabs/zed-opencv/blob/d8ffafc5b8fbabf8504102bdfb22caad073f04f2/python/zed-opencv.py#L50-L53

shouldn't it be the other way around?
```
def save_point_cloud(zed, filename) :    
print("Saving Point Cloud...")    
tmp = sl.Mat()    
zed.retrieve_measure(tmp, sl.MEASURE.XYZRGBA)
```

and

```
def save_depth(zed, filename) :    
print("Saving Depth Map...")    
tmp = sl.Mat()    
zed.retrieve_measure(tmp, sl.MEASURE. DEPTH)
```

**Comment by P-yver** [comment]
Indeed, the following commit fix it: https://github.com/stereolabs/zed-opencv/commit/4be02395ad0a4255c215e56c53b6582e1aca82c6

Thank you for the remark.
