### ISSUE TITLE
Camera bugs out on run. slMat2cvMat is in wrong place.

### ISSUE THREAD

**Issue by SegunAwe05** [stereolabs/zed-opencv#90]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, feature request, or anything other than a bug report directly related to this project.

### Description

when you cv::Mat img = slMat2cvMat that should be inside the while loop. I had a problem where If it is outside the while loop it causes your imshow image to glitch out very bad when you run. This tutorial tells us to put it outside the while loop

### Steps to Reproduce

1.Follow the this tutorial
2.
3.
...

### Expected Result

Clear camera images

### Actual Result

Glitchy camera images

### ZED Camera model

ZED Mini

### Environment

```shell
OS Ubuntu
Zed mini 3.5
Jetson Nano
```

**Comment by P-yver** [comment]
Hi,
In this sample, the function is call [outside the main loop](https://github.com/stereolabs/zed-opencv/blob/master/cpp/src/main.cpp#L86) but the corresponding memory `depth_image_zed` is already allocated.
If your source sl::Mat is not allocated, or has changed (type, size, mem) the corresponding cv::Mat reference is outdated.
